apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: karmada-operator-webhook
  namespace: karmada-system
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: karmada-operator-webhook
  namespace: karmada-operator-webhook-system
spec:
  dnsNames:
    - karmada-operator-webhook.karmada-system.svc
    - karmada-operator-webhook.karmada-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: karmada-operator-webhook
  secretName: karmada-operator-webhook-server-cert